### ISSUE TITLE
全新虚拟机下的环境···报错了

### ISSUE THREAD

**Issue by 0x0019** [shellfeel/Ant-AntV#3]
D:\bypass\Ant-AntV-master>python gen_trojan.py
D:\bypass\Ant-AntV-master\resource/
Traceback (most recent call last):
  File "gen_trojan.py", line 87, in <module>
    gen()
  File "gen_trojan.py", line 81, in gen
    create_cipher_beacon()
  File "D:\bypass\Ant-AntV-master\tmp_deal.py", line 28, in create_cipher_beacon
    main()
  File "D:\bypass\Ant-AntV-master\tmp_deal.py", line 12, in main
    with open(project_path.add_abs_path("/step2.py"), "r+", encoding="utf-8") as f1:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\bypass\\Ant-AntV-master/step2.py'

**Comment by shellfeel** [comment]
修复了，重新拉下代码，昨天变更了下分支。

**Comment by 0x0019** [comment]
好的 师傅
