### ISSUE TITLE
客户端运行生成后的马，报错了

### ISSUE THREAD

**Issue by 0x0019** [shellfeel/Ant-AntV#4]
Traceback (most recent call last):
  File "C:\Program Files\python\Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 16, in <module>
    import pkg_resources
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "pkg_resources\__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'

**Comment by shellfeel** [comment]
是生成的exe运行报错吗？
可以提供更多的信息吗（操作系统、位数、内存cpu）

**Comment by 0x0019** [comment]
> 是生成的exe运行报错吗？ 可以提供更多的信息吗（操作、暴露、内存cpu）

是的，win10 64位 intel-i5 10代 16G 内存

**Comment by shellfeel** [comment]
这个链接可能会解决你的问题，https://stackoverflow.com/questions/61574984/no-module-named-pkg-resources-py2-warn-pyinstaller
